# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deephaven/proto/extensions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n deephaven/proto/extensions.proto\x12!io.deephaven.proto.backplane.grpc\x1a google/protobuf/descriptor.proto\"-\n\nRpcOptions\x12\x1f\n\x17requires_authentication\x18\x01 \x01(\x08:g\n\x0brpc_options\x12\x1e.google.protobuf.MethodOptions\x18\xd7\x86\x03 \x01(\x0b\x32-.io.deephaven.proto.backplane.grpc.RpcOptions\x88\x01\x01\x42\x46H\x01P\x00Z@github.com/deephaven/deephaven-core/go/internal/proto/extensionsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deephaven.proto.extensions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(rpc_options)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001P\000Z@github.com/deephaven/deephaven-core/go/internal/proto/extensions'
  _RPCOPTIONS._serialized_start=105
  _RPCOPTIONS._serialized_end=150
# @@protoc_insertion_point(module_scope)
