version: "3.4"

services:
  deephaven:
    image: ghcr.io/deephaven/server:0.16.0-python
    labels:
      - 'traefik.http.routers.deephaven.rule=Host(`localhost`)'
    volumes:
      - ./data:/data
    environment:
      - JAVA_OPTS=-Xmx4g

  notebooks:
    image: ghcr.io/devinrsmith/webdav:latest
    labels:
      - 'traefik.http.routers.notebooks.rule=PathPrefix(`/notebooks/`)'
      - 'traefik.http.routers.notebooks.priority=100'
    volumes:
      - ./notebooks:/srv/webdav

  reverse-proxy:
    image: traefik:v2.8
    command:
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
    ports:
      - "${DEEPHAVEN_PORT:-10000}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro